# Generated by Django 3.2.10 on 2021-12-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Cancel', 'Cancel'), ('ReShedule', 'ReShedule'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
