# Generated by Django 3.2.10 on 2021-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Cancel', 'Cancel'), ('ReSchedule', 'ReSchedule'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
