# Generated by Django 3.2.10 on 2021-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitedoctor',
            name='email',
        ),
        migrations.AddField(
            model_name='invitedoctor',
            name='invite_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
